### ISSUE TITLE
ComplexStat

### ISSUE THREAD

**Issue by maniolek** [monitool/monitool-backend#3]
Response from API for basic(/complexStat, GET)  query doesn't contains data field.

**Comment by DamianChodorek** [comment]
@maniolek It's because ComplexStat is defined in wrong way. Period is in ms and it should be big enough so that proper values from Data can be used. Also sensorId is important. Make sure that Data that you taking under consideration is from proper sensor.

I defined some ComplexStat for you to use:

http://monitool.herokuapp.com:80/api/complexStat?access_token=GxKritPrjNJ6dYkDbTrI65o2d3wkxX8eCDEJ4r4SKFjq7WzGCLiPivilLQGt3An8

**Comment by maniolek** [comment]
Great, thanks! But even if the period is invalid figure,  response should
always have field with data, despite of the fact that no results has been
found.
9 kwi 2015 19:10 "DamianChodorek" notifications@github.com napisał(a):
